#ifndef __GAME_COMMON_SKILL_H__
#define __GAME_COMMON_SKILL_H__

#define LIFT_HEIGHT	56

#define SHORT_REST_TIMEOUT	2000
#define LONG_REST_TIMEOUT	3000
#define BE_THROW_REST_TIMEOUT	500
#define BE_LIFT_REST_TIMEOUT	4500

#define XSPEED_RUN	60
#define XSPEED_WALK	15
#define YSPEED_WALK	8
#define XACC_STOPRUN	20
#define XACC_DASH	10
#define ZSPEED_JUMP	60
#define ZACC_JUMP	22

#define XSPEED_S_HIT_FLY	55
#define ZACC_S_HIT_FLY		7
#define ZSPEED_S_HIT_FLY	15

#define XACC_ROLL	15

#define XSPEED_WEAK_WALK 20

#define XSPEED_X_HIT_FLY	70
#define ZACC_XB_HIT_FLY		15
#define ZSPEED_XB_HIT_FLY	25
#define ZACC_XF_HIT_FLY		50
#define ZSPEED_XF_HIT_FLY	100

#define XSPEED_X_HIT_FLY2	20
#define ZACC_XF_HIT_FLY2	10
#define ZSPEED_XF_HIT_FLY2	15

#define XSPEED_HIT_FLY	20
#define ZSPEED_HIT_FLY	100
#define ZACC_HIT_FLY	50

#define ROLL_TIMEOUT	200

#define XSPEED_THROWUP_FLY	60
#define XSPEED_THROWDOWN_FLY	70
#define ZSPEED_THROWUP_FLY	60
#define ZSPEED_THROWDOWN_FLY	40
#define ZACC_THROWUP_FLY	30
#define ZACC_THROWDOWN_FLY	40

#define SKILLNAME_A_ATTACK		"A attack"
#define SKILLNAME_B_ATTACK		"B attack"
#define SKILLNAME_JUMP			"jump"
#define SKILLNAME_JUMP_A_ATTACK		"jump A attack"
#define SKILLNAME_JUMP_B_ATTACK		"jump B attack"
#define SKILLNAME_JUMP_MACH_A_ATTACK	"jump mach A attack"
#define SKILLNAME_JUMP_MACH_B_ATTACK	"jump mach B attack"
#define SKILLNAME_SPRINT_A_ATTACK	"sprint A attack"
#define SKILLNAME_SPRINT_B_ATTACK	"sprint B attack"
#define SKILLNAME_SPRINT_JUMP_A_ATTACK	"sprint jump A attack"
#define SKILLNAME_SPRINT_JUMP_B_ATTACK	"sprint jump B attack"
#define SKILLNAME_MACH_A_ATTACK		"mach A attack"
#define SKILLNAME_MACH_B_ATTACK		"mach B attack"
#define SKILLNAME_A_FINALBLOW		"A final blow"
#define SKILLNAME_B_FINALBLOW		"B final blow"
#define SKILLNAME_JUMP_ELBOW		"jump elbow"
#define SKILLNAME_JUMP_TREAD		"jump tread"
#define SKILLNAME_A_LIFT		"A lift"
#define SKILLNAME_B_LIFT		"B lift"
#define SKILLNAME_A_THROW		"A throw"
#define SKILLNAME_B_THROW		"B throw"
#define SKILLNAME_MACH_STOMP		"mach stomp"
#define SKILLNAME_BOMBKICK		"bomb kick"
#define SKILLNAME_SPINHIT		"spin hit"
#define SKILLNAME_RIDE			"ride"
#define SKILLNAME_RIDE_A_ATTACK		"ride A attack"
#define SKILLNAME_RIDE_B_ATTACK		"ride B attack"
#define SKILLNAME_CATCH			"catch"
#define SKILLNAME_BIG_ELBOW		"big elbow"
#define SKILLNAME_PUSH			"push"

enum SkillPriority_AAttack {
	SKILLPRIORITY_A_LIFT,
	SKILLPRIORITY_A_THROW,
	SKILLPRIORITY_MACH_STOMP,
	SKILLPRIORITY_JUMP_ELBOW,
	SKILLPRIORITY_A_FINALBLOW,
	SKILLPRIORITY_SPINHIT,
	SKILLPRIORITY_SPRINT_A_ATTACK,
	SKILLPRIORITY_SPRINT_JUMP_A_ATTACK,
	SKILLPRIORITY_BIG_ELBOW,
	SKILLPRIORITY_JUMP_MACH_A_ATTACK,
	SKILLPRIORITY_JUMP_A_ATTACK,
	SKILLPRIORITY_MACH_A_ATTACK,
	SKILLPRIORITY_A_ATTACK,
	SKILLPRIORITY_RIDE_A_ATTACK
};

enum SkillPriority_BAttack {
	SKILLPRIORITY_B_LIFT,
	SKILLPRIORITY_B_THROW,
	SKILLPRIORITY_JUMP_TREAD,
	SKILLPRIORITY_B_FINALBLOW,
	SKILLPRIORITY_BOMBKICK,
	SKILLPRIORITY_SPRINT_B_ATTACK,
	SKILLPRIORITY_SPRINT_JUMP_B_ATTACK,
	SKILLPRIORITY_JUMP_MACH_B_ATTACK,
	SKILLPRIORITY_JUMP_B_ATTACK,
	SKILLPRIORITY_PUSH,
	SKILLPRIORITY_MACH_B_ATTACK,
	SKILLPRIORITY_B_ATTACK,
	SKILLPRIORITY_RIDE_B_ATTACK
};

enum SkillPriority_HorizMotion {
	SKILLPRIORITY_RIDE
};

enum SkillPriority_VertiMotion {
	SKILLPRIORITY_CATCH
};

enum SkillPriority_Jump {
	SKILLPRIORITY_JUMP
};

/** 注册通用技能 */
void CommonSkill_Register(void);

#endif
